name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
<<<<<<< HEAD
=======
  pull_request:
    branches: [ main ]
>>>>>>> 88a00e336213dea245915fc449abaaa8dabb5594

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - run: pytest tests -v
=======
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
          - name: Install dependencies
          run: |
          ls
          cat requirements.txt
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run Tests
        run: pytest tests/ -v

      - name: Deploy (Simulation)
        run: echo "Simulated deployment"
>>>>>>> 88a00e336213dea245915fc449abaaa8dabb5594
